# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket  = "terragrunt-288866261642"
    encrypt = true
    key     = "dev/terraform.tfstate"
    region  = "us-west-2"
  }
}
